### ISSUE TITLE
Missing ot_lib.py file in tools folder

### ISSUE THREAD

**Issue by WendyQi-Guo** [v-manhlt3/m-LTM-Audio-Text-Retrieval#1]
Hello,

It seems that the tools folder is missing the ot_lib.py file, which should contain the entropic_orlicz_wasserstein function. This file's absence leads to errors when trying to call this function from the codebase.

Could you please add ot_lib.py to the repository, or provide guidance on how to implement the entropic_orlicz_wasserstein function if it is not available?

Thank you for your assistance!

**Comment by v-manhlt3** [comment]
Hi,

The ``Orcliz loss`` is unused; therefore, you can ignore it and use the repo. I pushed a new commit to fix the issue.
